// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
// Navigation order + section labels, regenerated by /nexis:wiki each sync.
// `undefined` until the first build, in which case Starlight autogenerates.
import { sidebar } from './nexis-sidebar.mjs';
// i18n locale registry, rewritten wholesale by /nexis:wiki-translate.
import { defaultLocale, locales } from './nexis-locales.mjs';

// Generated by nexis:wiki --target starlight (scripts/bootstrap-starlight.mjs).
export default defineConfig({
  integrations: [
    // must come before starlight() — astro-mermaid hooks the markdown pipeline
    // Starlight otherwise owns, so it needs first refusal on ```mermaid fences.
    mermaid({
      autoTheme: true,
    }),
    starlight({
      title: 'Stemolly',
      description: 'AI tutoring platform knowledge wiki',
      defaultLocale,
      locales,
      // Wider layout on big screens + Mermaid zoom lightbox styles.
      customCss: ['./src/styles/nexis-wiki.css'],
      // Prev/Next pager that captions each link with its section, so
      // same-titled pages in different sections (every "Overview") are distinct.
      components: {
        Pagination: './src/components/Pagination.astro',
      },
      // Click-to-zoom for Mermaid diagrams (self-contained, offline).
      head: [
        {
          tag: 'script',
          attrs: { src: '/nexis-mermaid-zoom.js', defer: true },
        },
      ],
      // Explicit nav from the note taxonomy; falls back to autogeneration
      // (Starlight's default) while `sidebar` is still undefined.
      ...(sidebar ? { sidebar } : {}),
    }),
  ],
});
